[project]
name = "grid-risk-forecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "lewis.lea@cantab.net" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
grid-risk-forecast = "grid_risk_forecast:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
